import {
  MapPin,
  ChevronDown,
  ChevronUp,
  Bell,
  Search,
  Heart,
  Clock,
  Flame,
  Utensils,
  ShoppingBag,
  Home,
  User,
  DollarSign,
  ChefHat,
  Star,
  CheckCircle2,
  Truck,
  BarChart2,
  MessageSquare,
  Plus,
  ArrowLeft,
  MoreVertical,
  CreditCard,
  MessageCircle,
  HelpCircle,
  Check,
  LogOut,
  Settings,
  Grid,
  Menu,
  ChevronRight,
  TrendingUp,
  ShoppingBasket
} from 'lucide-react-native';

export const icons = {
  location: MapPin,
  expandMore: ChevronDown,
  expandLess: ChevronUp,
  notifications: Bell,
  search: Search,
  favorite: Heart,
  time: Clock,
  calories: Flame,
  restaurant: Utensils,
  cart: ShoppingBag,
  basket: ShoppingBasket,
  home: Home,
  profile: User,
  earnings: DollarSign,
  chef: ChefHat,
  rating: Star,
  checkCircle: CheckCircle2,
  delivery: Truck,
  stats: BarChart2,
  reviews: MessageSquare,
  add: Plus,
  back: ArrowLeft,
  menuMore: MoreVertical,
  card: CreditCard,
  chat: MessageCircle,
  help: HelpCircle,
  check: Check,
  logout: LogOut,
  settings: Settings,
  grid: Grid,
  menu: Menu,
  chevronRight: ChevronRight,
  trendingUp: TrendingUp,
};

export type IconType = keyof typeof icons;
